services:
  # Development services
  postgres:
    image: postgres:16.3
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: serverpod_challenge
      POSTGRES_PASSWORD: "wacdVfiKysgA7EFBRFoXfrASkSYb2PAI"
    volumes:
      - serverpod_challenge_data:/var/lib/postgresql/data
    profiles:
      - '' # Default profile
      - dev
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "znxqffNG5KQUV69-zLwuLSROPVZFEz7g"
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles:
      - '' # Default profile
      - dev

  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - '9090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: serverpod_challenge_test
      POSTGRES_PASSWORD: "DpK_cYO8Sb55lnf200xyxubcxNIT1COE"
    volumes:
      - serverpod_challenge_test_data:/var/lib/postgresql/data
    profiles:
      - '' # Default profile
      - test
  redis_test:
    image: redis:6.2.6
    ports:
      - '9091:6379'
    command: redis-server --requirepass "vi4maY3EN9qPim3URI4LFFvBTPyT0mSC"
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles:
      - '' # Default profile
      - test

volumes:
  serverpod_challenge_data:
  serverpod_challenge_test_data:
